In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [3]:
guns = pd.read_csv("guns_2013.csv")

In [4]:
guns

   state  death_rate  gun_rate  Unnamed: 3  Unnamed: 4
0     AL       17.79      48.9         NaN         NaN
1     AK       19.59      61.7         NaN         NaN
2     AZ       14.20      32.3         NaN         NaN
3     AR       16.93      57.9         NaN         NaN
4     CA        7.89      20.1         NaN         NaN
5     CO       11.75      34.3         NaN         NaN
6     CT        4.48      16.6         NaN         NaN
7     DE       10.80       5.2         NaN         NaN
8     FL       11.00      32.5         NaN         NaN
9     GA       12.49      31.6         NaN         NaN
10    HI       12.63      45.1         NaN         NaN
11    ID        2.71      56.9         NaN         NaN
12    IL       14.08      26.2         NaN         NaN
13    IN        8.67      33.8         NaN         NaN
14    IA       13.04      33.8         NaN         NaN
15    KS        8.19      32.2         NaN         NaN
16    KY       11.44      42.4         NaN         NaN
17    LA       14.15      44.5         NaN         NaN
18    ME       19.15      22.6         NaN         NaN
19    MD       11.89      20.7         NaN         NaN
20    MA        9.75      22.6         NaN         NaN
21    MI        3.18      28.8         NaN         NaN
22    MN       12.03      36.7         NaN         NaN
23    MS        7.88      42.8         NaN         NaN
24    MO       17.55      27.1         NaN         NaN
25    MT       14.56      52.3         NaN         NaN
26    NE       16.94      19.8         NaN         NaN
27    NV        8.99      37.5         NaN         NaN
28    NH       14.16      14.4         NaN         NaN
29    NJ        7.03      11.3         NaN         NaN
30    NM        5.69      49.9         NaN         NaN
31    NY       15.63      10.3         NaN         NaN
32    NC        4.39      28.7         NaN         NaN
33    ND       12.42      47.9         NaN         NaN
34    OH       11.89      19.6         NaN         NaN
35    OK       11.14      31.2         NaN         NaN
36    OR       16.41      26.6         NaN         NaN
37    PA       11.76      27.1         NaN         NaN
38    RI       11.36       5.8         NaN         NaN
39    SC        5.33      44.4         NaN         NaN
40    SD       15.60      35.0         NaN         NaN
41    TN        9.47      39.4         NaN         NaN
42    TX       15.86      35.7         NaN         NaN
43    UT       10.50      31.9         NaN         NaN
44    VT       11.69      28.8         NaN         NaN
45    VA       10.37      29.3         NaN         NaN
46    WA       10.46      27.7         NaN         NaN
47    WV        9.07      54.2         NaN         NaN
48    WI       15.10      34.7         NaN         NaN
49    WY        9.93      53.8         NaN         NaN

In [12]:
#create scatterplot

plot1 = sns.regplot(x=guns["death_rate"], y=guns["gun_rate"], color="red")

for i, txt in enumerate(guns.state):
    plot1.annotate(txt, (guns.death_rate[i],guns.gun_rate[i]))

plt.title("Gun Ownership vs. Gun Deaths")
plt.xlabel("Gun ownership (percent of adults)")
plt.ylabel("Gun deaths per 100,000 residents")

sns.plt.show()